#!/usr/bin/env python3
"""
diag.py — woodworking diagram generation scripts.

Usage:
  python diag.py <slug> exploded   [--view iso]   [--factor 2.5] [--output path]
  python diag.py <slug> elevation  <view>          [--output path]
  python diag.py <slug> cutlist    [--cols 4]      [--output path]

Views: iso (default), front, back, side, left, top

Outputs go to projects/<slug>/exports/ unless --output is specified.

Model convention
----------------
Works with any show_object = cq.Assembly() using named parts.
Parts named <base>_<n> (e.g. rafter_0, rafter_1) are grouped automatically
in the cut list.  Optionally define DIAG_META in the model file:

    DIAG_META = {
        "rafter": {"label": "Rafter (birdsmouth)"},
        "sleeper": {"label": "Foundation Sleeper H4"},
    }

Shape extraction
----------------
asm.children gives leaf nodes.  Each child has:
  .shapes[0]  — the committed CadQuery Shape (post-cut, post-boolean)
  .loc        — cq.Location positioning it relative to the root assembly

world_shape = child.shapes[0].located(child.loc)

For parts built in world space (e.g. rafters built via .rotate().translate().cut()),
.loc is Identity and .shapes[0] IS already at world position, including all cuts.
For parts built at origin+loc (sleepers, posts), .located(loc) moves them to world
position.  Either way, the exact cut geometry is preserved in the BREP solid.
"""

import math
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from view import (
    PROJECTS_DIR, VIEWS, _make_svg, _x_dir,
    find_model_file, load_show_object, svg_to_png,
)


# ── Shared geometry helpers ───────────────────────────────────────────────────

def _cross3(a, b):
    return (
        a[1]*b[2] - a[2]*b[1],
        a[2]*b[0] - a[0]*b[2],
        a[0]*b[1] - a[1]*b[0],
    )


def _dot3(a, b):
    return a[0]*b[0] + a[1]*b[1] + a[2]*b[2]


def _up_dir(proj_dir, x_dir):
    """Vertical axis in the projected image: cross(proj_dir, x_dir)."""
    return _cross3(proj_dir, x_dir)


def _world_to_svg(pt, x_dir, up_dir, unit_scale, x_translate, y_translate):
    """Map a 3D world point to SVG pixel coords using the same transform as _make_svg."""
    proj_x = _dot3(pt, x_dir)
    proj_y = _dot3(pt, up_dir)
    svg_x = (proj_x + x_translate) * unit_scale
    svg_y = -(proj_y + y_translate) * unit_scale   # SVG Y-axis is downward
    return svg_x, svg_y


def _svg_transform_params(svg_text):
    """
    Extract (unit_scale, x_translate, y_translate) from SVG generated by _make_svg.

    The transform attribute in the SVG groups looks like:
      transform="scale(0.375, -0.375) translate(533.3, -2053.4)"
    """
    m = re.search(
        r'transform="scale\(([^,]+),\s*-([^)]+)\)\s+translate\(([^,]+),\s*([^)]+)\)"',
        svg_text,
    )
    if not m:
        return 1.0, 0.0, 0.0
    unit_scale  = float(m.group(1).strip())
    x_translate = float(m.group(3).strip())
    y_translate = float(m.group(4).strip())
    return unit_scale, x_translate, y_translate


# ── Assembly introspection ────────────────────────────────────────────────────

def iter_parts(asm):
    """
    Yield (name, world_shape, color) for all direct leaf children of a cq.Assembly.

    world_shape is the Shape with all boolean operations (cuts, unions) already
    committed, positioned in assembly world space.
    """
    for child in asm.children:
        if not child.shapes:
            continue
        world_shape = child.shapes[0].located(child.loc)
        yield child.name, world_shape, child.color


def _part_base_name(name):
    """'rafter_0' → 'rafter',  'knee_L_1' → 'knee_L',  'plate_front' → 'plate_front'."""
    return re.sub(r'_\d+$', '', name)


def _load_assembly(slug):
    """
    Execute the model file once and return (obj, namespace, proj_dir_path).

    Executing once avoids side effects (budget.json writes, etc.) that would
    occur if the file were run again to extract DIAG_META or other module-level
    data.  The full namespace is returned so callers can read any variable.
    """
    proj_dir_path = PROJECTS_DIR / slug
    model_file    = find_model_file(proj_dir_path)
    print(f"  Model    : {model_file.name}")
    src = model_file.read_text()
    ns  = {"__file__": str(model_file), "__name__": "__main__"}
    try:
        exec(compile(src, str(model_file), "exec"), ns)
    except Exception as e:
        print(f"error: Model error in {model_file.name}: {e}", file=sys.stderr)
        sys.exit(1)
    obj = ns.get("show_object")
    if obj is None:
        print(f"error: {model_file.name} does not set show_object", file=sys.stderr)
        sys.exit(1)
    return obj, ns, proj_dir_path


# ── Subcommand: exploded view ─────────────────────────────────────────────────

def cmd_exploded(slug, view="iso", factor=2.5, output=None):
    """
    Render an exploded assembly view.

    Each part is offset radially from the assembly centroid by
    (part_centroid - asm_centroid) * (factor - 1).  factor=1.0 gives the
    assembled position; factor=2.5 spreads parts clearly apart.
    """
    import cadquery as cq
    obj, _, proj_dir_path = _load_assembly(slug)

    if isinstance(obj, cq.Assembly):
        shape = _build_exploded(obj, factor)
    elif isinstance(obj, cq.Workplane):
        shape = obj.val()
    else:
        shape = obj  # already a Shape

    exports = proj_dir_path / "exports"
    exports.mkdir(exist_ok=True)
    svg_path = exports / "_tmp_exploded.svg"
    png_path = Path(output) if output else exports / f"exploded_{view}.png"

    svg_text = _make_svg(shape, VIEWS.get(view, VIEWS["iso"]), opts={
        "width": 1400, "height": 900,
        "showHidden": True,
        "strokeWidth": -1,
        "strokeColor": (0, 0, 0),
        "hiddenColor": (160, 160, 160),
    })
    svg_path.write_text(svg_text)
    svg_to_png(svg_path, png_path)
    svg_path.unlink(missing_ok=True)
    print(f"  Saved    : {png_path}")


def _build_exploded(asm, factor):
    """Return a Compound with each part offset radially from the assembly centroid."""
    import cadquery as cq

    whole_bb = asm.toCompound().BoundingBox()
    cx = (whole_bb.xmin + whole_bb.xmax) / 2
    cy = (whole_bb.ymin + whole_bb.ymax) / 2
    cz = (whole_bb.zmin + whole_bb.zmax) / 2

    exploded = cq.Assembly()
    for name, world_shape, color in iter_parts(asm):
        bb = world_shape.BoundingBox()
        px = (bb.xmin + bb.xmax) / 2
        py = (bb.ymin + bb.ymax) / 2
        pz = (bb.zmin + bb.zmax) / 2

        dx = (px - cx) * (factor - 1)
        dy = (py - cy) * (factor - 1)
        dz = (pz - cz) * (factor - 1)

        kw = dict(name=name, loc=cq.Location(cq.Vector(dx, dy, dz)))
        if color is not None:
            kw["color"] = color
        exploded.add(world_shape, **kw)

    return exploded.toCompound()


# ── Subcommand: elevation with annotations ────────────────────────────────────

def cmd_elevation(slug, view_name, output=None):
    """
    Render an orthographic elevation with overall dimension annotations and scale bar.

    Dimensions annotated:
      front/back  — overall width (X) + overall height (Z)
      side/left   — overall depth (Y) + overall height (Z)
      top         — overall width (X) + overall depth (Y)
    """
    import cadquery as cq
    obj, _, proj_dir_path = _load_assembly(slug)
    print(f"  View     : {view_name}")

    if isinstance(obj, cq.Assembly):
        shape = obj.toCompound()
    elif isinstance(obj, cq.Workplane):
        shape = obj.val()
    else:
        shape = obj

    proj_dir_vec = VIEWS.get(view_name, VIEWS["front"])
    W, H = 1600, 1000

    svg_opts = {
        "width": W, "height": H,
        "marginLeft": 250, "marginTop": 80,
        "showHidden": True,
        "strokeWidth": -1,
        "strokeColor": (0, 0, 0),
        "hiddenColor": (160, 160, 160),
    }
    svg_text = _make_svg(shape, proj_dir_vec, opts=svg_opts)

    unit_scale, x_translate, y_translate = _svg_transform_params(svg_text)
    xdir   = _x_dir(proj_dir_vec)
    up_dir = _up_dir(proj_dir_vec, xdir)

    bb3 = shape.BoundingBox()
    ann = _build_elevation_annotations(
        bb3, proj_dir_vec, xdir, up_dir,
        unit_scale, x_translate, y_translate, W, H,
    )
    svg_text = svg_text.replace("</svg>", ann + "\n</svg>")

    exports = proj_dir_path / "exports"
    exports.mkdir(exist_ok=True)
    svg_path = exports / f"_tmp_elev_{view_name}.svg"
    png_path = Path(output) if output else exports / f"elevation_{view_name}.png"

    svg_path.write_text(svg_text)
    svg_to_png(svg_path, png_path, width=W, height=H)
    svg_path.unlink(missing_ok=True)
    print(f"  Saved    : {png_path}")


def _horiz_dim(x1, x2, y, label, offset=-35, color="#1a6bb5", fs=13):
    """Horizontal dimension line.  offset < 0 → above the y baseline."""
    yd = y + offset
    ext_len = abs(offset) + 8
    sign = -1 if offset < 0 else 1
    return (
        # Extension lines
        f'<line x1="{x1:.1f}" y1="{y:.1f}" x2="{x1:.1f}" y2="{yd + sign*6:.1f}" '
        f'stroke="{color}" stroke-width="0.8"/>'
        f'<line x1="{x2:.1f}" y1="{y:.1f}" x2="{x2:.1f}" y2="{yd + sign*6:.1f}" '
        f'stroke="{color}" stroke-width="0.8"/>'
        # Main line
        f'<line x1="{x1:.1f}" y1="{yd:.1f}" x2="{x2:.1f}" y2="{yd:.1f}" '
        f'stroke="{color}" stroke-width="1.3"/>'
        # Arrowheads (pointing inward)
        f'<polygon points="{x1:.1f},{yd:.1f} {x1+9:.1f},{yd-3:.1f} {x1+9:.1f},{yd+3:.1f}" fill="{color}"/>'
        f'<polygon points="{x2:.1f},{yd:.1f} {x2-9:.1f},{yd-3:.1f} {x2-9:.1f},{yd+3:.1f}" fill="{color}"/>'
        # Label
        f'<text x="{(x1+x2)/2:.1f}" y="{yd - 6:.1f}" text-anchor="middle" '
        f'dominant-baseline="auto" font-family="monospace" font-size="{fs}" fill="{color}">{label}</text>'
    )


def _vert_dim(x, y1, y2, label, offset=-35, color="#1a6bb5", fs=13):
    """Vertical dimension line.  offset < 0 → left of the x baseline."""
    xd = x + offset
    sign = -1 if offset < 0 else 1
    my = (y1 + y2) / 2
    return (
        # Extension lines
        f'<line x1="{x:.1f}" y1="{y1:.1f}" x2="{xd + sign*6:.1f}" y2="{y1:.1f}" '
        f'stroke="{color}" stroke-width="0.8"/>'
        f'<line x1="{x:.1f}" y1="{y2:.1f}" x2="{xd + sign*6:.1f}" y2="{y2:.1f}" '
        f'stroke="{color}" stroke-width="0.8"/>'
        # Main line
        f'<line x1="{xd:.1f}" y1="{y1:.1f}" x2="{xd:.1f}" y2="{y2:.1f}" '
        f'stroke="{color}" stroke-width="1.3"/>'
        # Arrowheads (pointing inward)
        f'<polygon points="{xd:.1f},{y1:.1f} {xd-3:.1f},{y1+9:.1f} {xd+3:.1f},{y1+9:.1f}" fill="{color}"/>'
        f'<polygon points="{xd:.1f},{y2:.1f} {xd-3:.1f},{y2-9:.1f} {xd+3:.1f},{y2-9:.1f}" fill="{color}"/>'
        # Label (rotated)
        f'<text transform="translate({xd - 8:.1f},{my:.1f}) rotate(-90)" '
        f'text-anchor="middle" font-family="monospace" font-size="{fs}" fill="{color}">{label}</text>'
    )


def _scale_bar(x, y, bar_mm, unit_scale, color="#333", fs=12):
    """Horizontal scale bar at SVG position (x, y)."""
    bar_px = bar_mm * unit_scale
    return (
        f'<line x1="{x:.1f}" y1="{y:.1f}" x2="{x+bar_px:.1f}" y2="{y:.1f}" '
        f'stroke="{color}" stroke-width="3"/>'
        f'<line x1="{x:.1f}" y1="{y-5:.1f}" x2="{x:.1f}" y2="{y+5:.1f}" stroke="{color}" stroke-width="2"/>'
        f'<line x1="{x+bar_px:.1f}" y1="{y-5:.1f}" x2="{x+bar_px:.1f}" y2="{y+5:.1f}" stroke="{color}" stroke-width="2"/>'
        f'<text x="{x + bar_px/2:.1f}" y="{y - 9:.1f}" text-anchor="middle" '
        f'font-family="monospace" font-size="{fs}" fill="{color}">{round(bar_mm)} mm</text>'
    )


def _nice_round(mm):
    """Round to a clean scale-bar value (100, 200, 250, 500, 1000, …)."""
    if mm <= 0:
        return 100
    exp = 10 ** math.floor(math.log10(mm))
    for n in (1, 2, 2.5, 5, 10):
        if n * exp >= mm:
            return n * exp
    return exp * 10


def _build_elevation_annotations(bb3, proj_dir, x_dir, up_dir,
                                  unit_scale, x_translate, y_translate, W, H):
    def to_svg(pt):
        return _world_to_svg(pt, x_dir, up_dir, unit_scale, x_translate, y_translate)

    # Project all 8 corners of the 3D bounding box to find SVG extents.
    xn, xx = bb3.xmin, bb3.xmax
    yn, yx = bb3.ymin, bb3.ymax
    zn, zx = bb3.zmin, bb3.zmax
    corners_svg = [
        to_svg((xn, yn, zn)), to_svg((xx, yn, zn)),
        to_svg((xn, yx, zn)), to_svg((xx, yx, zn)),
        to_svg((xn, yn, zx)), to_svg((xx, yn, zx)),
        to_svg((xn, yx, zx)), to_svg((xx, yx, zx)),
    ]
    sx_all = [c[0] for c in corners_svg]
    sy_all = [c[1] for c in corners_svg]
    min_sx, max_sx = min(sx_all), max(sx_all)
    min_sy, max_sy = min(sy_all), max(sy_all)

    parts = [f'<g id="annotations" font-family="monospace">']

    # Determine which world dimensions map to horizontal / vertical in this view.
    # x_dir dotted against world axes tells us which world axis is "horizontal".
    # up_dir dotted against world axes tells us which is "vertical".
    ax_world = [(1,0,0), (0,1,0), (0,0,1)]
    ax_label = ["X", "Y", "Z"]
    ax_len   = [bb3.xlen, bb3.ylen, bb3.zlen]

    # Horizontal annotation: axis most aligned with x_dir
    h_idx = max(range(3), key=lambda i: abs(_dot3(x_dir, ax_world[i])))
    # Vertical annotation: axis most aligned with up_dir
    v_idx = max(range(3), key=lambda i: abs(_dot3(up_dir, ax_world[i])))

    h_len = round(ax_len[h_idx])
    v_len = round(ax_len[v_idx])

    # Width/depth dimension line (horizontal — above the model)
    if h_len > 0:
        parts.append(_horiz_dim(min_sx, max_sx, min_sy, f"{h_len} mm", offset=-40))

    # Height dimension line (vertical — left of the model)
    if v_len > 0:
        parts.append(_vert_dim(min_sx, min_sy, max_sy, f"{v_len} mm", offset=-50))

    # Scale bar (bottom-left, sized to ~1/6 of horizontal span)
    bar_mm = _nice_round((max_sx - min_sx) / unit_scale / 6)
    parts.append(_scale_bar(50, H - 35, bar_mm, unit_scale))

    # View label (bottom-right)
    parts.append(
        f'<text x="{W - 20:.0f}" y="{H - 15:.0f}" text-anchor="end" '
        f'font-size="14" fill="#888">view: {_view_name_for(proj_dir)}</text>'
    )

    parts.append("</g>")
    return "\n".join(parts)


def _view_name_for(proj_dir):
    for name, d in VIEWS.items():
        if tuple(d) == tuple(proj_dir):
            return name
    return str(proj_dir)


# ── Subcommand: cut list ──────────────────────────────────────────────────────

def cmd_cutlist(slug, cols=4, output=None):
    """
    Render a cut list: every unique part laid out as a 2D profile with dimensions.

    Parts with identical base names (e.g. rafter_0 … rafter_N) are grouped and
    shown once with a ×N count label.

    For each part the profile projection axis is chosen automatically:
      look along the SMALLEST bounding-box dimension (= the thickness direction).
    This means rafters project along their 45 mm width, showing the exact side
    profile including birdsmouth notches; knee braces show their angled ends, etc.
    """
    import cadquery as cq

    obj, ns, proj_dir_path = _load_assembly(slug)
    if not isinstance(obj, cq.Assembly):
        print("  Error    : cutlist requires show_object = cq.Assembly()")
        sys.exit(1)

    # DIAG_META is read from the already-executed namespace — no re-execution needed.
    diag_meta = ns.get("DIAG_META", {})

    # Group by base name, preserving insertion order
    groups = {}
    for name, world_shape, color in iter_parts(obj):
        base = _part_base_name(name)
        groups.setdefault(base, []).append(world_shape)

    print(f"  Parts    : {len(groups)} types  ({sum(len(v) for v in groups.values())} total pieces)")

    exports = proj_dir_path / "exports"
    exports.mkdir(exist_ok=True)
    svg_path = exports / "_tmp_cutlist.svg"
    png_path = Path(output) if output else exports / "cutlist.png"

    cell_w, cell_h = 400, 280
    label_h = 52
    pad = 20
    rows = math.ceil(len(groups) / cols)
    master_w = cols * (cell_w + pad) + pad
    master_h = rows * (cell_h + label_h + pad) + pad

    cells = []
    for idx, (base, shapes) in enumerate(groups.items()):
        row, col = divmod(idx, cols)
        ox = pad + col * (cell_w + pad)
        oy = pad + row * (cell_h + label_h + pad)

        rep_shape = shapes[0]
        count = len(shapes)

        # Projection direction = along smallest bounding-box dimension
        bb = rep_shape.BoundingBox()
        smallest_axis = min(
            [(bb.xlen, (1., 0., 0.)), (bb.ylen, (0., 1., 0.)), (bb.zlen, (0., 0., 1.))],
            key=lambda t: t[0],
        )[1]

        # Cell background + border
        cells.append(
            f'<rect x="{ox}" y="{oy}" width="{cell_w}" height="{cell_h}" '
            f'fill="white" stroke="#bbb" stroke-width="1"/>'
        )
        # Render part profile directly via HLR — no SVG template parsing
        cells.append(_cell_group(rep_shape, smallest_axis, ox, oy, cell_w, cell_h))

        # Dimension label from 3D bounding box (L × W × T, sorted descending)
        dims = sorted([round(bb.xlen), round(bb.ylen), round(bb.zlen)], reverse=True)
        dim_str = f"{dims[0]} × {dims[1]} × {dims[2]} mm"

        meta  = diag_meta.get(base, {})
        label = meta.get("label", base.replace("_", " "))
        count_tag = f" ×{count}" if count > 1 else ""

        lx = ox + cell_w / 2
        ly = oy + cell_h + 17
        cells += [
            f'<text x="{lx:.0f}" y="{ly:.0f}" text-anchor="middle" '
            f'font-family="monospace" font-size="13" fill="#111">'
            f'<tspan font-weight="bold">{label}</tspan>'
            f'<tspan fill="#c05000">{count_tag}</tspan></text>',
            f'<text x="{lx:.0f}" y="{ly+18:.0f}" text-anchor="middle" '
            f'font-family="monospace" font-size="11" fill="#555">{dim_str}</text>',
        ]

    master = (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{master_w}" height="{master_h}">\n'
        f'<rect width="{master_w}" height="{master_h}" fill="#f0f0f0"/>\n'
        + "\n".join(cells) +
        "\n</svg>"
    )

    svg_path.write_text(master)
    svg_to_png(svg_path, png_path, width=master_w, height=master_h)
    svg_path.unlink(missing_ok=True)
    print(f"  Saved    : {png_path}")


def _cell_group(shape, look_along, ox, oy, cell_w, cell_h, margin=20):
    """
    Render shape directly via HLR and return an SVG <g> element positioned at (ox,oy).

    Bypasses _make_svg / SVG_TEMPLATE entirely so there is no XML parsing — the
    output is a single, self-contained <g> with known-valid structure.
    """
    from cadquery.occ_impl.exporters.svg import getPaths
    from cadquery.occ_impl.shapes import Shape, Compound, TOLERANCE
    from OCP.gp import gp_Ax2, gp_Pnt, gp_Dir
    from OCP.BRepLib import BRepLib
    from OCP.HLRBRep import HLRBRep_Algo, HLRBRep_HLRToShape
    from OCP.HLRAlgo import HLRAlgo_Projector

    xd = _x_dir(look_along)

    hlr = HLRBRep_Algo()
    hlr.Add(shape.wrapped)
    hlr.Projector(HLRAlgo_Projector(gp_Ax2(gp_Pnt(), gp_Dir(*look_along), gp_Dir(*xd))))
    hlr.Update()
    hlr.Hide()

    hlr_out = HLRBRep_HLRToShape(hlr)
    vis_occ = []
    for getter in (hlr_out.VCompound, hlr_out.Rg1LineVCompound, hlr_out.OutLineVCompound):
        s = getter()
        if not s.IsNull():
            vis_occ.append(s)

    if not vis_occ:
        return f'<g transform="translate({ox},{oy})"></g>'

    for el in vis_occ:
        BRepLib.BuildCurves3d_s(el, TOLERANCE)

    vis_shapes = list(map(Shape, vis_occ))
    # getPaths(visible_shapes, hidden_shapes) → (hidden_paths, visible_paths)
    _, path_data = getPaths(vis_shapes, [])

    if not path_data:
        return f'<g transform="translate({ox},{oy})"></g>'

    bb = Compound.makeCompound(vis_shapes).BoundingBox()
    us = min(
        (cell_w - 2 * margin) / max(bb.xlen, 1e-6),
        (cell_h - 2 * margin) / max(bb.ylen, 1e-6),
    )
    xt = (0 - bb.xmin) + margin / us
    yt = (0 - bb.ymax) - margin / us
    sw = 1.0 / us

    paths = "".join(f'<path d="{p}"/>' for p in path_data)
    return (
        f'<g transform="translate({ox},{oy})">'
        f'<g fill="none" stroke="#1e1e1e" stroke-width="{sw:.6f}"'
        f' transform="scale({us:.6f},-{us:.6f}) translate({xt:.4f},{yt:.4f})">'
        f'{paths}'
        f'</g>'
        f'</g>'
    )


# ── CLI entry point ───────────────────────────────────────────────────────────

def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _flag(args, name, default=None):
    if name in args:
        i = args.index(name)
        if i + 1 < len(args):
            return args[i + 1]
    return default


def main():
    args = sys.argv[1:]
    if len(args) < 2 or args[0].startswith("-"):
        print(__doc__)
        sys.exit(0)

    slug, cmd = args[0], args[1]

    if not (PROJECTS_DIR / slug).exists():
        die(f"Project '{slug}' not found in {PROJECTS_DIR}")

    if cmd == "exploded":
        cmd_exploded(
            slug,
            view=_flag(args, "--view", "iso"),
            factor=float(_flag(args, "--factor", 2.5)),
            output=_flag(args, "--output"),
        )

    elif cmd == "elevation":
        if len(args) < 3 or args[2].startswith("-"):
            die(f"elevation requires a view name: {', '.join(VIEWS)}")
        vname = args[2]
        if vname not in VIEWS:
            die(f"Unknown view '{vname}'. Choose from: {', '.join(VIEWS)}")
        cmd_elevation(slug, vname, output=_flag(args, "--output"))

    elif cmd == "cutlist":
        cmd_cutlist(
            slug,
            cols=int(_flag(args, "--cols", 4)),
            output=_flag(args, "--output"),
        )

    else:
        die(f"Unknown command '{cmd}'. Use: exploded, elevation, cutlist")


if __name__ == "__main__":
    main()
